#all: 
#	g++ cross_section.cpp -o cross_section -I/home/tianyu/lib/pythia8230/include -O2  -pedantic -W -Wall -Wshadow -fPIC -L/home/tianyu/lib/pythia8230/lib -Wl,-rpath,/home/tianyu/lib/pythia8230/lib -lpythia8 -ldl 
pythia: 
	g++ cross_section_pythia.cpp -o cross_section_pythia -I/home/tianyu/lib/pythia8230/include -O2  -pedantic -W -Wall -Wshadow -fPIC -L/home/tianyu/lib/pythia8230/lib -Wl,-rpath,/home/tianyu/lib/pythia8230/lib -lpythia8 -ldl
example: 
	g++ example.cpp -o example -I/home/tianyu/lib/pythia8230/include -O2  -pedantic -W -Wall -Wshadow -fPIC -L/home/tianyu/lib/pythia8230/lib -Wl,-rpath,/home/tianyu/lib/pythia8230/lib -lpythia8 -ldl
